openapi: 3.1.0
info:
  description: survey-dingdong API
  title: Survey DingDong
  version: 1.0.0
servers:
- url: /
paths:
  /auth/refresh:
    post:
      operationId: refresh_token_auth_refresh_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Refresh Token
      tags:
      - Auth
      x-eov-operation-handler: controllers/AuthController
  /users:
    get:
      operationId: get_user_list_users_get
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          title: Page
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          title: Size
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GetUserListResponse'
                type: array
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Get User List
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
    post:
      operationId: create_user_users_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create User
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /users/me:
    get:
      operationId: get_user_me_users_me_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserListResponse'
          description: Successful Response
      security:
      - PermissionDependency: []
      summary: Get User Me
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /users/login:
    post:
      operationId: login_users_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Login
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /workspaces:
    get:
      operationId: get_workspace_list_workspaces_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GetWorkspaceListResponse'
                type: array
          description: Successful Response
      security:
      - PermissionDependency: []
      summary: Get Workspace List
      tags:
      - Workspace
      x-eov-operation-handler: controllers/WorkspaceController
    post:
      operationId: create_workspace_workspaces_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkspaceRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWorkspaceResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Create Workspace
      tags:
      - Workspace
      x-eov-operation-handler: controllers/WorkspaceController
  /workspaces/{workspace_id}:
    delete:
      operationId: delete_workspace_workspaces__workspace_id__delete
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Delete Workspace
      tags:
      - Workspace
      x-eov-operation-handler: controllers/WorkspaceController
    patch:
      operationId: update_workspace_workspaces__workspace_id__patch
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkspaceRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Update Workspace
      tags:
      - Workspace
      x-eov-operation-handler: controllers/WorkspaceController
  /workspaces/{workspace_id}/projects:
    get:
      operationId: get_project_list_workspaces__workspace_id__projects_get
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: project_type
        required: true
        schema:
          $ref: '#/components/schemas/ProjectTypeEnum'
        style: form
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          title: Page
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          title: Size
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GetProjectListResponse'
                type: array
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Get Project List
      tags:
      - Project
      x-eov-operation-handler: controllers/ProjectController
    post:
      operationId: create_project_workspaces__workspace_id__projects_post
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: project_type
        required: true
        schema:
          $ref: '#/components/schemas/ProjectTypeEnum'
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProjectResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Create Project
      tags:
      - Project
      x-eov-operation-handler: controllers/ProjectController
  /workspaces/{workspace_id}/projects/{project_id}:
    delete:
      operationId: delete_project_workspaces__workspace_id__projects__project_id__delete
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: project_type
        required: true
        schema:
          $ref: '#/components/schemas/ProjectTypeEnum'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Delete Project
      tags:
      - Project
      x-eov-operation-handler: controllers/ProjectController
    get:
      operationId: get_project_workspaces__workspace_id__projects__project_id__get
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: project_type
        required: true
        schema:
          $ref: '#/components/schemas/ProjectTypeEnum'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetExperimentProjectResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Get Project
      tags:
      - Project
      x-eov-operation-handler: controllers/ProjectController
    put:
      operationId: update_project_workspaces__workspace_id__projects__project_id__put
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: project_type
        required: true
        schema:
          $ref: '#/components/schemas/ProjectTypeEnum'
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutProjectRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Update Project
      tags:
      - Project
      x-eov-operation-handler: controllers/ProjectController
  /workspaces/{workspace_id}/projects/{project_id}/participants:
    get:
      operationId: get_project_participant_list_workspaces__workspace_id__projects__project_id__participants_get
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: project_type
        required: true
        schema:
          $ref: '#/components/schemas/ProjectTypeEnum'
        style: form
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          title: Page
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          title: Size
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GetExperimentParticipantResponse'
                type: array
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Get Project Participant List
      tags:
      - Project
      x-eov-operation-handler: controllers/ProjectController
  /workspaces/{workspace_id}/projects/{project_id}/participants/{participant_id}:
    delete:
      operationId: delete_project_participant_workspaces__workspace_id__projects__project_id__participants__participant_id__delete
      parameters:
      - explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          title: Workspace Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: participant_id
        required: true
        schema:
          title: Participant Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: project_type
        required: true
        schema:
          $ref: '#/components/schemas/ProjectTypeEnum'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - PermissionDependency: []
      summary: Delete Project Participant
      tags:
      - Project
      x-eov-operation-handler: controllers/ProjectController
components:
  schemas:
    CreateProjectRequest:
      example:
        title: title
      properties:
        title:
          description: Title
          title: Title
          type: string
      required:
      - title
      title: CreateProjectRequest
    CreateProjectResponse:
      example:
        id: 0
      properties:
        id:
          description: ID
          title: Id
          type: integer
      required:
      - id
      title: CreateProjectResponse
    CreateUserRequest:
      example:
        password2: password2
        password1: password1
        email: email
        username: username
      properties:
        email:
          description: Email
          format: email
          title: Email
          type: string
        password1:
          description: Password1
          format: password
          title: Password1
          type: string
          writeOnly: true
        password2:
          description: Password2
          format: password
          title: Password2
          type: string
          writeOnly: true
        username:
          description: username
          title: Username
          type: string
      required:
      - email
      - password1
      - password2
      - username
      title: CreateUserRequest
    CreateUserResponse:
      example:
        email: email
        username: username
      properties:
        email:
          description: Email
          title: Email
          type: string
        username:
          description: username
          title: Username
          type: string
      required:
      - email
      - username
      title: CreateUserResponse
    CreateWorkspaceRequest:
      example:
        title: title
      properties:
        title:
          description: Title
          title: Title
          type: string
      required:
      - title
      title: CreateWorkspaceRequest
    CreateWorkspaceResponse:
      example:
        id: 0
      properties:
        id:
          description: ID
          title: Id
          type: integer
      required:
      - id
      title: CreateWorkspaceResponse
    ExperimentAttendanceStatus:
      enum:
      - scheduled
      - not_attended
      - attended
      title: ExperimentAttendanceStatus
      type: string
    ExperimentTimeslotRead:
      example:
        start_time: start_time
        end_time: end_time
        id: 6
        max_participants: 1
      properties:
        id:
          description: ID
          title: Id
          type: integer
        start_time:
          description: Experiment start time
          format: time
          title: Start Time
          type: string
        end_time:
          description: Experiment end time
          format: time
          title: End Time
          type: string
        max_participants:
          description: Maximum number of experiment participants
          title: Max Participants
          type: integer
      required:
      - end_time
      - id
      - max_participants
      - start_time
      title: ExperimentTimeslotRead
    ExperimentTimeslotRequest:
      example:
        start_time: start_time
        end_time: end_time
        id: 0
        max_participants: 6
      properties:
        id:
          nullable: true
          type: integer
        start_time:
          description: Experiment start time
          format: time
          title: Start Time
          type: string
        end_time:
          description: Experiment end time
          format: time
          title: End Time
          type: string
        max_participants:
          description: Maximum number of experiment participants
          title: Max Participants
          type: integer
      required:
      - end_time
      - max_participants
      - start_time
      title: ExperimentTimeslotRequest
    ExperimentTypeEnum:
      enum:
      - online
      - offline
      title: ExperimentTypeEnum
      type: string
    GetExperimentParticipantResponse:
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        reserved_date: reserved_date
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 0
        attendance_status: ""
        username: username
      properties:
        id:
          description: Participant ID
          title: Id
          type: integer
        username:
          description: Username
          title: Username
          type: string
        reserved_date:
          description: Reserved Date
          title: Reserved Date
          type: string
        attendance_status:
          allOf:
          - $ref: '#/components/schemas/ExperimentAttendanceStatus'
          description: Attendance Status
        created_at:
          description: Created datetime
          format: date-time
          title: Created At
          type: string
        updated_at:
          description: Updated datetime
          format: date-time
          title: Updated At
          type: string
      required:
      - attendance_status
      - created_at
      - id
      - reserved_date
      - updated_at
      - username
      title: GetExperimentParticipantResponse
    GetExperimentProjectResponse:
      example:
        end_date: 2000-01-23
        excluded_dates:
        - 2000-01-23
        - 2000-01-23
        description: description
        created_at: 2000-01-23T04:56:07.000+00:00
        title: title
        experiment_type: null
        updated_at: 2000-01-23T04:56:07.000+00:00
        participant_code: participant_code
        is_public: true
        experiment_timeslots:
        - start_time: start_time
          end_time: end_time
          id: 6
          max_participants: 1
        - start_time: start_time
          end_time: end_time
          id: 6
          max_participants: 1
        location: location
        id: 0
        start_date: 2000-01-23
      properties:
        id:
          description: ID
          title: Id
          type: integer
        title:
          description: Title
          title: Title
          type: string
        description:
          nullable: true
          type: string
        is_public:
          description: Whether the project is public
          title: Is Public
          type: boolean
        start_date:
          description: Experiment start date
          format: date
          title: Start Date
          type: string
        end_date:
          description: Experiment end date
          format: date
          title: End Date
          type: string
        excluded_dates:
          description: Experimental exclusion days
          items:
            format: date
            type: string
          type: array
        experiment_timeslots:
          description: Time information of experiment
          items:
            $ref: '#/components/schemas/ExperimentTimeslotRead'
          type: array
        experiment_type:
          $ref: '#/components/schemas/ExperimentTypeEnum'
        location:
          description: Experiment location
          title: Location
          type: string
        participant_code:
          description: Experiment participant code
          title: Participant Code
          type: string
        created_at:
          description: Created datetime
          format: date-time
          title: Created At
          type: string
        updated_at:
          description: Updated datetime
          format: date-time
          title: Updated At
          type: string
      required:
      - created_at
      - end_date
      - excluded_dates
      - experiment_timeslots
      - experiment_type
      - id
      - is_public
      - location
      - participant_code
      - start_date
      - title
      - updated_at
      title: GetExperimentProjectResponse
    GetProjectListResponse:
      example:
        workspace_id: 6
        updated_at: 2000-01-23T04:56:07.000+00:00
        is_public: true
        description: description
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 0
        title: title
        joined_participants: 1
        max_participants: 5
      properties:
        id:
          description: ID
          title: Id
          type: integer
        workspace_id:
          description: Workspace ID
          title: Workspace Id
          type: integer
        title:
          description: Title
          title: Title
          type: string
        description:
          nullable: true
          type: string
        is_public:
          description: Whether the project is public
          title: Is Public
          type: boolean
        joined_participants:
          description: Number of experiment participants
          title: Joined Participants
          type: integer
        max_participants:
          description: Maximum number of experiment participants
          title: Max Participants
          type: integer
        created_at:
          format: date-time
          title: Created At
          type: string
        updated_at:
          format: date-time
          title: Updated At
          type: string
      required:
      - created_at
      - id
      - is_public
      - joined_participants
      - max_participants
      - title
      - updated_at
      - workspace_id
      title: GetProjectListResponse
    GetUserListResponse:
      example:
        id: 0
        email: email
        username: username
      properties:
        id:
          description: ID
          title: Id
          type: integer
        email:
          description: Email
          title: Email
          type: string
        username:
          description: username
          title: Username
          type: string
      required:
      - email
      - id
      - username
      title: GetUserListResponse
    GetWorkspaceListResponse:
      example:
        order_no: 6
        id: 0
        title: title
      properties:
        id:
          description: ID
          title: Id
          type: integer
        title:
          description: Title
          title: Title
          type: string
        order_no:
          description: Order
          title: Order No
          type: integer
      required:
      - id
      - order_no
      - title
      title: GetWorkspaceListResponse
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    LoginRequest:
      example:
        password: password
        email: email
      properties:
        email:
          description: Email
          format: email
          title: Email
          type: string
        password:
          description: Password
          title: Password
          type: string
      required:
      - email
      - password
      title: LoginRequest
    LoginResponse:
      example:
        refresh_token: refresh_token
        token: token
      properties:
        token:
          description: Token
          title: Token
          type: string
        refresh_token:
          description: Refresh token
          title: Refresh Token
          type: string
      required:
      - refresh_token
      - token
      title: LoginResponse
    ProjectTypeEnum:
      enum:
      - survey
      - experiment
      title: ProjectTypeEnum
      type: string
    PutProjectRequest:
      example:
        end_date: 2000-01-23
        excluded_dates:
        - 2000-01-23
        - 2000-01-23
        is_public: true
        description: description
        experiment_timeslots:
        - start_time: start_time
          end_time: end_time
          id: 0
          max_participants: 6
        - start_time: start_time
          end_time: end_time
          id: 0
          max_participants: 6
        location: location
        title: title
        experiment_type: null
        start_date: 2000-01-23
      properties:
        title:
          description: Title
          title: Title
          type: string
        description:
          description: Description
          title: Description
          type: string
        is_public:
          description: Whether the project is public
          title: Is Public
          type: boolean
        start_date:
          format: date
          title: Start Date
          type: string
          ddescription: Experiment start date
        end_date:
          description: Experiment end date
          format: date
          title: End Date
          type: string
        excluded_dates:
          description: Experimental exclusion days
          items:
            format: date
            type: string
          type: array
        experiment_timeslots:
          description: Time information of experiment
          items:
            $ref: '#/components/schemas/ExperimentTimeslotRequest'
          type: array
        experiment_type:
          $ref: '#/components/schemas/ExperimentTypeEnum'
        location:
          description: Experiment location
          title: Location
          type: string
      required:
      - description
      - end_date
      - excluded_dates
      - experiment_timeslots
      - experiment_type
      - is_public
      - location
      - start_date
      - title
      title: PutProjectRequest
    RefreshTokenRequest:
      example:
        refresh_token: refresh_token
        token: token
      properties:
        token:
          description: Token
          title: Token
          type: string
        refresh_token:
          description: Refresh token
          title: Refresh Token
          type: string
      required:
      - refresh_token
      - token
      title: RefreshTokenRequest
    RefreshTokenResponse:
      example:
        refresh_token: refresh_token
        token: token
      properties:
        token:
          description: Token
          title: Token
          type: string
        refresh_token:
          description: Refresh token
          title: Refresh Token
          type: string
      required:
      - refresh_token
      - token
      title: RefreshTokenResponse
    UpdateWorkspaceRequest:
      example:
        order_no: 0
        title: title
      properties:
        title:
          nullable: true
          type: string
        order_no:
          nullable: true
          type: integer
      title: UpdateWorkspaceRequest
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer
  securitySchemes:
    PermissionDependency:
      in: header
      name: Authorization
      type: apiKey
